version: '3'

networks:
  api:
      name: api
      attachable: true
  host:
    driver: bridge

volumes:
  postgres_data:

services:
  pg:
    image: 'postgres:14'
    restart: always
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - postgres_data:/db
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345'
      PGDATA: '/db'
  ip_api:
    build:
      context: .
    depends_on:
      - pg
    restart: always
    ports:
      - '8081:80'
    links:
      - pg
    networks:
      - api
      - host