version: '3'

networks:
  api:
      name: api
      attachable: true
  apps:
    external: true
  host:
    driver: bridge

volumes:
  postgres_data:

services:
  pg:
    image: 'postgres:14'
    restart: always
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - postgres_data:/db
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Gerutsfjkfdhjdghvdyietuf'
      PGDATA: '/db'
  ip_api:
    build:
      context: .
    depends_on:
      - pg
    restart: always
    ports:
      - '3500:80'
    links:
      - pg
    networks:
      - api
      - host
      - apps
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/alive"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 15s
